### PR TITLE
feat: primary images

### PR DESCRIPTION
**Pull request by hay-kot**
Add support for setting a primary image for items

image

Also makes some visual changes on the location/labels pages

CleanShot 2023-10-06 at 21 16 13@2x

### CODE REVIEW

**Comment by dominch** [comment]
I just wanted to check that feature, 
I have latest image, nothing changes so far, 
So I found button for "set primary photos" it warned me that this can't be undone, why? :) I decided to take that risk and it "failed to set primary photos".. 

In logs: 

```
10:48AM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/actions/set-primary-photos rid=homebox-5765964694-bgmzk/P6g2sRVg3F-023934
10:48AM ERR ../go/src/app/app/api/handlers/v1/v1_ctrl_actions.go:25 > failed to run action error="ent: attachment not found" action_ref="ensure asset IDs"
10:48AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="ent: attachment not found" req_id=homebox-5765964694-bgmzk/P6g2sRVg3F-023934
10:48AM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/actions/set-primary-photos rid=homebox-5765964694-bgmzk/P6g2sRVg3F-023934 status=500
10:48AM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=GET path=/api/v1/ws/events rid=homebox-5765964694-bgmzk/P6g2sRVg3F-022086 status=0
```

should I add anything to system for this functionality? any system lib? probably I need to adjust image with something like imagemagick?

**Comment by pyrho** [comment]
@dominch I wasn't sure how to do this either but I found out eventually,

https://github.com/hay-kot/homebox/assets/145502/43980c89-56d5-4bef-b2b6-db98ef90b430

**Comment by dominch** [comment]
> @dominch I wasn't sure how to do this either but I found out eventually,
> 
>  CleanShot.2023-11-23.at.23.28.43-converted.mp4

Thanks for detailed instruction, this certainly makes it much easier to understand :) 
But it's not working on my side, set primary action drops 500 error (which is internal server error) and same thing from Your video shows photo on gallery but not on item so probably still something is wrong. I think that on helm release something to rescale image is missing on server.

**Comment by pyrho** [comment]
I worked as I showed on the picture, but now the images display as broken links on my end.

**Comment by bee-eater** [comment]
@pyrho Same here. The images are broken after some time. For me it helps to delete the cookies, then everything works again as expected.

**Pull request merged**
