### PR TITLE
Add New Detail Type :: Image

### PR DESCRIPTION
**Pull request by phyesix**
## What type of PR is this?
- feature

## What this PR does / why we need it:
- If there is an image attached I would like to see it

## Special notes for your reviewer:

I have developed a util function that works with the same logic as the url in a simple way and we can understand whether it is an image or not.

### CODE REVIEW

**Comment by hay-kot** [comment]
Hey, thanks for the PR!

Why would you want to use this instead of an attachment?

**Comment by phyesix** [comment]
Hi, thank you for your effort for homebox. 

Actually I don't know why, but maybe you can find external image URL from internet. So it can also be a useful solution for those with storage problems.

**Comment by JigSawFr** [comment]
Can be great to set an image to show what the item is, at top. Why not also set an attachement image to fill it

**Comment by hay-kot** [comment]
> Hi, thank you for your effort for homebox.
>
> Actually I don't know why, but maybe you can find external image URL from internet. So it can also be a useful solution for those with storage problems.

If there isn't a specific reason to use this over the current image support, I'm inclined not to merge this. I do plan to add support for marking an image as the primary image so it will show in the top. If you have a more specific reason you'd want to see this in Homebox let me know. 

Thanks!

**Pull request closed without merging**
